import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SearchBar from "@/components/SearchBar";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "MAYA: Build your Dream Team!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-screen`}>
        <div className="flex flex-col gap-6 px-6 pt-6 py-24">
          <SearchBar />
          {children}
        </div>
        <Navbar />
      </body>
    </html>
  );
}
